name: Structur3.co
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#676766'
    - '#f3f3f4'
    - '#3a3a39'
    - '#8c8c8d'
  brandStrength: 0.7243584794923663
  lightness: 0.2735526154283434
  saturation: 0.6771700801327825
  rhythmicContrast: 0.0000226746778935194
purpose: []
